Metrics/MethodLength:
  Max: 14

Naming/UncommunicativeMethodParamName:
  Exclude:
    - 'app/controllers/graphql_controller.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Metrics/LineLength:
  Max: 119
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

require: rubocop-performance

Documentation:
  Enabled: false

AllCops:
  Exclude:
    - vendor/**/*
    - db/**/*
    - bin/**/*
    - tmp/**/*