Metrics/MethodLength:
  Max: 14

Naming/UncommunicativeMethodParamName:
  Exclude:
    - 'app/controllers/graphql_controller.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/graphql_controller.rb'
    - 'app/graphql/stjorn_backend_schema.rb'
    - 'app/graphql/types/base_interface.rb'
    - 'app/graphql/types/mutation_type.rb'
    - 'app/graphql/types/query_type.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Metrics/LineLength:
  Max: 119

require: rubocop-performance

AllCops:
  Exclude:
    - vendor/**/*
    - db/**/*
    - bin/**/*
    - tmp/**/*