require: rubocop-performance

Layout/AlignArray:
  Exclude:
    - spec/spec_helper.rb

Layout/IndentArray:
  Exclude:
    - spec/spec_helper.rb

Metrics/MethodLength:
  Max: 14
  Exclude:
    - spec/support/graphql/*

Naming/UncommunicativeMethodParamName:
  Exclude:
    - 'app/controllers/graphql_controller.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Metrics/LineLength:
  Max: 119

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Documentation:
  Enabled: false

AllCops:
  Exclude:
    - vendor/**/*
    - db/**/*
    - bin/**/*
    - tmp/**/*