default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: stjorn-dev

test:
  <<: *default
  database: stjorn-test

production:
  <<: *default
  database: stjorn-production
  username: stjorn
  password: <%= ENV['STJORN-BACKEND_DATABASE_PASSWORD'] %>
